import test from 'node:test';import assert from 'node:assert/strict';
import {Runtime} from '../src/runtime/graph.js';import {declareParameter,setParameter,startGoal,cancelGoal,lookup,transforms} from '../src/runtime/course.js';import {execute} from '../src/terminal/cli.js';import {TerminalSession} from '../src/terminal/session.js';
const runtime=()=>{const r=new Runtime();r.enableSession3();return r;};
test('parameter declaration, live updates and validation preserve the graph',()=>{const r=runtime();r.nodes.add('/node');declareParameter(r,'/node','speed',.2);const updates=[];r.parameterListeners.add((...v)=>updates.push(v));assert.match(execute(r,'ros2 param list /node'),/speed/);assert.equal(execute(r,'ros2 param get /node speed'),'0.2');execute(r,'ros2 param set /node speed 0.6');assert.equal(updates[0][2],.6);assert.throws(()=>setParameter(r,'/node','speed','fast'));assert.throws(()=>setParameter(r,'/node','absent',1));r.reset();assert.equal(r.parameters.has('/node'),false);});
test('custom messages enforce their contract and share publication with CLI',()=>{const r=runtime();const received=[];r.ensureTopic('/target_info','ros2learn_interfaces/msg/TargetInfo');r.subscribe('/target_info','/reader',m=>received.push(m));execute(r,'ros2 topic pub --once /target_info ros2learn_interfaces/msg/TargetInfo {"visible":true,"position":"LEFT","confidence":0.8}');assert.equal(received[0].position,'LEFT');assert.throws(()=>r.publish('/target_info','ros2learn_interfaces/msg/TargetInfo',{visible:true,position:'LEFT',confidence:2}));assert.equal(received.length,1);});
test('action feedback follows physical travel, completes, rejects busy and cancels',()=>{const r=runtime(),events=[];const id=startGoal(r,'/client',{distance:1},(...v)=>events.push(v));assert.throws(()=>startGoal(r,'/other',{distance:1}));r.step(.8);assert.ok(events.some(([kind])=>kind==='feedback'));assert.ok(r.robot.x>0);r.step(2);assert.equal(r.goals.get(id).status,4);assert.ok(Math.abs(r.robot.distance-1)<.02);assert.equal(events.at(-1)[1].result.success,true);const second=startGoal(r,'/client',{distance:2});r.step(.4);assert.equal(cancelGoal(r,second),true);assert.equal(r.goals.get(second).status,5);const x=r.robot.x;r.step(1);assert.equal(r.robot.x,x);assert.equal(cancelGoal(r,second),false);assert.throws(()=>startGoal(r,'/client',{distance:NaN}));});
test('action terminal owns cancellation and cleans up its graph node',()=>{const r=runtime(),output=[];const t=new TerminalSession(r,1,s=>output.push(s));assert.equal(execute(r,'ros2 action type /drive_distance'),'ros2learn_interfaces/action/DriveDistance');t.run('ros2 action send_goal /drive_distance ros2learn_interfaces/action/DriveDistance {"distance":1} --feedback');r.step(.6);assert.ok(output.some(s=>s.includes('Feedback')));t.stop();assert.equal(t.running,false);assert.equal(r.nodes.has('/ros2cli_action_1'),false);assert.equal(r.robot.linear,0);});
test('TF tree composes and inverts sensor and target frames',()=>{const r=runtime();r.robot.x=1;r.robot.y=2;r.robot.yaw=Math.PI/2;r.targetFrame=[3,4];const t=lookup(r,'odom','laser_link');assert.ok(Math.abs(t.x-1)<1e-9);assert.ok(Math.abs(t.y-2.2)<1e-9);const relative=lookup(r,'base_link','target');assert.ok(Math.abs(relative.x-2)<1e-9);assert.ok(Math.abs(relative.y+2)<1e-9);const inverse=lookup(r,'laser_link','odom');assert.ok(Math.abs(inverse.x+2.2)<1e-9);assert.equal(transforms(r).transforms.length,5);assert.throws(()=>lookup(r,'missing','odom'));});
test('reset service stops an active action without deleting subscriptions',()=>{const r=runtime();const id=startGoal(r,'/client',{distance:1});r.subscribe('/scan','/reader',()=>{});r.step(.4);r.callService('/reset_robot','std_srvs/srv/Trigger');assert.equal(r.goals.get(id).status,5);assert.equal(r.robot.distance,0);assert.ok(r.nodes.has('/reader'));});
