import test from'node:test';import assert from'node:assert/strict';import{Lab}from'../src/lab.js';import{RuntimeAdapter}from'../src/runtime/adapter.js';
test('shared graph, echo, parameters and cleanup',async()=>{const lab=new Lab(),t=lab.terminal();const adapter=new RuntimeAdapter(lab.runtime);adapter.worker={postMessage(){},terminate(){}};adapter.handle({kind:'node',node:'/talker'});adapter.handle({kind:'publisher',node:'/talker',topic:'topic',type:'std_msgs/msg/String'});assert.match(await t.execute('ros2 node list'),/talker/);assert.match(await t.execute('ros2 topic info /topic'),/Publisher count: 1/);let received='';t.output=s=>received=s;await t.execute('ros2 topic echo /topic');adapter.handle({kind:'publish',node:'/talker',topic:'topic',type:'std_msgs/msg/String',message:{data:'actual'}});assert.match(received,/actual/);assert.equal(lab.runtime.topics.get('/topic').subscribers.size,1);lab.stop(t.id);assert.equal(lab.runtime.topics.get('/topic').subscribers.size,0);adapter.handle({kind:'parameter_declare',node:'/talker',name:'message_prefix',value:'Hello'});await t.execute('ros2 param set /talker message_prefix Hello');assert.equal(lab.runtime.parameters.get('/talker').get('message_prefix'),'Hello');adapter.stop();assert.equal(lab.runtime.nodes.size,0);assert.equal(lab.runtime.topics.size,2);lab.reset();});
test('interface show and package overlay per terminal',async()=>{const lab=new Lab(),a=lab.terminal(),b=lab.terminal();assert.match(await a.execute('ros2 interface show sensor_msgs/msg/PointCloud2'),/PointField/);await a.execute('mkdir -p ~/ros2_ws/src');await a.execute('cd ~/ros2_ws/src');await a.execute('ros2 pkg create --build-type ament_cmake --license Apache-2.0 empty');await a.execute('cd ..');await a.execute('colcon build');await assert.rejects(()=>a.execute('ros2 run empty hello'),/not found/);await a.execute('source install/setup.bash');assert.match(await a.execute('ros2 pkg list'),/empty/);assert.doesNotMatch(await b.execute('ros2 pkg list'),/empty/);lab.reset();});
test('topic pub -r is a real terminal-owned publisher, defaults and verbose endpoints',async()=>{const lab=new Lab(),t=lab.terminal(),other=lab.terminal();await t.execute("ros2 topic pub -r 5 /move geometry_msgs/msg/Twist '{linear: {x: 0.2}}'");assert.equal(lab.processes.active().length,1);assert.equal(lab.runtime.topics.get('/move').publishers.size,1);assert.match(await other.execute('ros2 topic info /move -v'),/_ros2cli_pub/);const sample=[...lab.runtime.samples.values()].at(-1);assert.equal(sample.message.angular.z,0);lab.close(t.id);assert.equal(lab.runtime.nodes.size,0);assert.equal(lab.runtime.jobs.size,0);assert.equal(lab.runtime.topics.size,2);await assert.rejects(()=>other.execute("ros2 topic pub --once /x std_msgs/msg/String '{data: 12}'"),/string/);lab.reset();});

test('base ROS topics expose real types, events, counts and cleanup',async()=>{
 const lab=new Lab(),inspect=lab.terminal(),logs=lab.terminal(),events=lab.terminal();
 assert.equal(await inspect.execute('ros2 topic list'),'/parameter_events\n/rosout');
 assert.equal(await inspect.execute('ros2 topic type /rosout'),'rcl_interfaces/msg/Log');
 assert.match(await inspect.execute('ros2 topic info /parameter_events'),/Type: rcl_interfaces\/msg\/ParameterEvent\nPublisher count: 1\nSubscription count: 0/);
 let log='',event='';logs.output=s=>log=s;events.output=s=>event=s;
 await logs.execute('ros2 topic echo /rosout');await events.execute('ros2 topic echo /parameter_events');assert.equal(log,'');assert.equal(event,'');
 const adapter=new RuntimeAdapter(lab.runtime);adapter.worker={postMessage(){},terminate(){}};adapter.handle({kind:'node',node:'/demo'});
 adapter.handle({kind:'log',node:'/demo',level:30,text:'Real warning'});assert.match(log,/Real warning/);assert.match(log,/"level": 30/);
 adapter.handle({kind:'parameter_declare',node:'/demo',name:'rate',value:2,value_type:3});assert.match(event,/"new_parameters"/);assert.match(event,/"double_value": 2/);
 await inspect.execute('ros2 param set /demo rate 3.5');const value=JSON.parse(event.split('\n---')[0]);assert.equal(value.changed_parameters[0].value.double_value,3.5);
 adapter.stop();lab.stop(logs.id);lab.close(events.id);
 assert.equal(await inspect.execute('ros2 topic info /rosout'),'Type: rcl_interfaces/msg/Log\nPublisher count: 1\nSubscription count: 0');assert.equal(lab.runtime.nodes.size,0);
 lab.reset();assert.equal(lab.runtime.topics.size,2);assert.equal(lab.runtime.listeners.size,0);
 await assert.rejects(()=>inspect.execute('ros2 topit type /rosout'),/invalid choice: 'topit'/);assert.match(await inspect.execute('ros2 param'),/ros2 param list/);
});
