// Shared source for the generated first-paint shell in every public HTML page.
const bootstrap=function(){const root=document.documentElement;let theme='dark',lang='en';try{theme=localStorage.getItem('ros2learn-theme')||theme;lang=localStorage.getItem('ros2learn-language')||lang;}catch{}root.dataset.theme=theme==='light'?'light':'dark';root.lang=['en','nl','fr','es','de','pt','it'].includes(lang)?lang:'en';root.dataset.kinenestBoot='loading';root.dataset.kinenestReady='false';let timer,finished=false;const end=()=>{root.dataset.kinenestBoot='ready';};const fail=message=>{if(finished)return;finished=true;clearTimeout(timer);const show=()=>{root.dataset.kinenestBoot='error';const cover=document.getElementById('kn-boot-cover');if(!cover)return;cover.setAttribute('aria-hidden','false');cover.querySelector('.boot-error').hidden=false;cover.querySelector('.boot-error-detail').textContent=message||'A required file did not load. Check your connection and reload.';};if(document.body)show();else document.addEventListener('DOMContentLoaded',show,{once:true});};const ready=async()=>{if(finished)return;await Promise.all([...document.querySelectorAll('.brand-icon,#kn-boot-cover img')].map(image=>image.decode?.().catch(()=>{})));await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));if(finished)return;finished=true;clearTimeout(timer);root.dataset.kinenestReady='true';root.dataset.kinenestBoot='revealing';window.dispatchEvent(new Event('kinenestready'));if(matchMedia('(prefers-reduced-motion: reduce)').matches)end();else setTimeout(end,180);};window.KineNestBoot={ready,fail};timer=setTimeout(()=>fail('Page setup did not finish. Check your connection and reload to retry.'),10000);window.addEventListener('pageshow',event=>{if(event.persisted&&root.dataset.kinenestReady==='true')end();});};
const css="html{background:#08141d;color-scheme:dark}html[data-theme=light]{background:#f0f5f7;color-scheme:light}#kn-boot-cover{display:none}html[data-kinenest-boot=loading] body>:not(#kn-boot-cover):not(noscript),html[data-kinenest-boot=error] body>:not(#kn-boot-cover):not(noscript){visibility:hidden}html[data-kinenest-boot=loading] #kn-boot-cover,html[data-kinenest-boot=revealing] #kn-boot-cover,html[data-kinenest-boot=error] #kn-boot-cover{position:fixed;inset:0;z-index:2000;display:flex;flex-direction:column;align-items:center;justify-content:center;background:var(--bg,#08141d);color:var(--text,#e4edf0);opacity:1;pointer-events:none}html[data-theme=light] #kn-boot-cover{background:var(--bg,#f0f5f7);color:var(--text,#172f3c)}#kn-boot-cover>img{width:144px;height:144px;object-fit:contain}html[data-kinenest-boot=revealing] #kn-boot-cover{opacity:0;transition:opacity 160ms ease}html[data-kinenest-boot=error] #kn-boot-cover{pointer-events:auto}.boot-error{max-width:36rem;padding:1.5rem;font:16px/1.5 system-ui,sans-serif;text-align:center}.boot-error a{color:inherit}html[data-kinenest-boot=error] .boot-error-detail{overflow-wrap:anywhere}@media(prefers-reduced-motion:reduce){html[data-kinenest-boot=revealing] #kn-boot-cover{transition:none}}";
const cover="<div id=\"kn-boot-cover\" aria-hidden=\"true\"><img src=\"./public/assets/brand/kinenest-icon.png\" alt=\"\" width=\"144\" height=\"144\"><div class=\"boot-error\" hidden><h1>Page could not start</h1><p class=\"boot-error-detail\"></p><a href=\"\">Reload this page</a></div></div>";
export function pageShell(html){
 html=html.replace(/<!-- kn:head -->[\s\S]*?<!-- \/kn:head -->/g,'').replace(/<!-- kn:cover -->[\s\S]*?<!-- \/kn:cover -->/g,'');
 const head='<!-- kn:head --><script>('+bootstrap.toString()+')();</script><style>'+css+'</style><!-- /kn:head -->';
 html=html.replace(/<meta\s+charset=["']?utf-8["']?\s*\/?>(?:\r?\n)?/i,'');
 return html.replace('<head>','<head><meta charset="utf-8">'+head).replace(/<body([^>]*)>/,'<body$1><!-- kn:cover -->'+cover+'<!-- /kn:cover -->');
}
