import { setupBranding } from './product.js';
import additional from './translations.js';
const strings={
  'Run Python':['Python uitvoeren','Exécuter Python'],'Stop Python':['Python stoppen','Arrêter Python'],'Restore starter code':['Startcode herstellen','Restaurer le code initial'],'Reset lab':['Lab resetten','Réinitialiser le labo'],'Check solution':['Oplossing controleren','Vérifier la solution'],'Reveal next hint':['Volgende hint tonen','Afficher un indice'],'Python workspace':['Python-werkruimte','Espace Python'],'Robot world':['Robotwereld','Monde du robot'],'Live ROS graph':['Live ROS-graaf','Graphe ROS en direct'],'Shared ROS learning terminals':['Gedeelde ROS-leerterminals','Terminaux ROS partagés'],'+ New terminal':['+ Nieuwe terminal','+ Nouveau terminal'],'Show LiDAR rays':['LiDAR-stralen tonen','Afficher les rayons LiDAR'],'Show student centroid overlay':['Berekend zwaartepunt tonen','Afficher le centroïde calculé'],'Exercise':['Oefening','Exercice'],'Parameters':['Parameters','Paramètres'],'Action progress':['Actievoortgang','Progression de l’action'],'TF frames':['TF-frames','Repères TF'],'Subscribers & LiDAR':['Subscribers en LiDAR','Abonnements et LiDAR'],'Perception & services':['Perceptie en services','Perception et services'],'Parameters & actions':['Parameters en acties','Paramètres et actions'],'Odometry & frames':['Odometrie en frames','Odométrie et repères'],'Debugging & integration':['Debuggen en integratie','Débogage et intégration'],'Real Python and NumPy, running entirely in your browser.':['Echte Python en NumPy, volledig in je browser.','Python et NumPy réels, entièrement dans votre navigateur.'],'Exercise complete. Your code passed the behavioural checks.':['Oefening voltooid. Je code voldoet aan de gedragscontroles.','Exercice terminé. Votre code satisfait les vérifications du comportement.'],'Not complete yet. Review the checks, output and hints.':['Nog niet voltooid. Bekijk de controles, uitvoer en hints.','Pas encore terminé. Consultez les vérifications, la sortie et les indices.'],'Ready. Complete the TODOs and Run Python.':['Klaar. Vul de TODO’s aan en voer Python uit.','Prêt. Complétez les TODO puis exécutez Python.'],'Callbacks can update node state':['Callbacks kunnen de toestand van een node bijwerken','Les callbacks peuvent mettre à jour l’état du nœud'],'On a real ROS 2 machine':['Op een echte ROS 2-machine','Sur une vraie machine ROS 2']
};
Object.assign(strings,additional);
const originals=new Map();for(const [key,values]of Object.entries(strings)){originals.set(key,key);for(const value of values)originals.set(value,key);}
let lang='en';try{lang=localStorage.getItem('ros2learn-language')||'en';}catch{}if(!['en','nl','fr'].includes(lang))lang='en';
export const language=()=>lang;
export function translate(text){const prefix=text.match(/^[✓○] /)?.[0]??'';if(prefix)return prefix+translate(text.slice(prefix.length));const key=originals.get(text);return key?(lang==='en'?key:strings[key][lang==='nl'?0:1]):text;}
export function setupPreferences(){
  if(document.getElementById('preferences'))return;
  setupBranding();
  const controls=document.createElement('div');controls.id='preferences';
  controls.innerHTML='<label><span class="sr-only">Language</span><select id="language" aria-label="Language"><option value="en">🇬🇧 EN</option><option value="nl">🇳🇱 NL</option><option value="fr">🇫🇷 FR</option></select></label><button id="theme" type="button">Light</button><label><span class="sr-only">Layout</span><select id="layout" aria-label="Layout"><option value="split">Workbench</option><option value="stack">Stacked</option></select></label>';
  document.querySelector('header').append(controls);
  let theme='dark',layout='split';try{theme=localStorage.getItem('ros2learn-theme')||theme;layout=localStorage.getItem('ros2learn-layout')||layout;}catch{}
  const save=(key,value)=>{try{localStorage.setItem('ros2learn-'+key,value);}catch{}};
  const applyTheme=()=>{document.documentElement.dataset.theme=theme;document.getElementById('theme').textContent=theme==='dark'?({en:'Light',nl:'Licht',fr:'Clair'}[lang]):({en:'Dark',nl:'Donker',fr:'Sombre'}[lang]);};applyTheme();
  document.getElementById('theme').onclick=()=>{theme=theme==='dark'?'light':'dark';save('theme',theme);applyTheme();};
  const applyLayout=()=>{document.body.dataset.layout=layout;};applyLayout();document.getElementById('layout').value=layout;
  document.getElementById('layout').onchange=e=>{layout=e.target.value;save('layout',layout);applyLayout();};
  // One shared workbench: mission/code beside sensor feedback. Reading order stays meaningful.
  const mission=document.querySelector('.mission'),code=document.querySelector('.python-panel'),camera=document.querySelector('.camera-panel'),world=document.querySelector('.world-panel'),graph=document.querySelector('.graph-panel');
  if(code){code.insertBefore(code.querySelector('.python-buttons'),code.querySelector('textarea'));const box=document.createElement('div');box.className='workbench';const left=document.createElement('div'),right=document.createElement('div');left.className='workbench-code';right.className='workbench-sensors';document.querySelector('.vision-grid').before(box);box.append(left,right);left.append(mission,code);right.append(camera,world,graph);document.querySelectorAll('.vision-grid').forEach(el=>{if(!el.children.length)el.remove();});}
  const applyLanguage=()=>{document.documentElement.lang=lang;const labels={en:['Workbench','Stacked'],nl:['Werkbank','Onder elkaar'],fr:['Atelier','Empilé']}[lang];[...document.getElementById('layout').options].forEach((o,i)=>{if(o.textContent!==labels[i])o.textContent=labels[i];});const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const n=walker.currentNode;if(n.parentElement.closest('pre,code,textarea,script,style,#preferences'))continue;const value=n.textContent.trim(),translated=translate(value);if(value!==translated)n.textContent=n.textContent.replace(value,translated);}};
  document.getElementById('language').value=lang;document.getElementById('language').onchange=e=>{lang=e.target.value;save('language',lang);applyLanguage();applyTheme();window.dispatchEvent(new Event('languagechange'));};
  let queued=false;new MutationObserver(()=>{if(!queued){queued=true;queueMicrotask(()=>{queued=false;applyLanguage();});}}).observe(document.body,{childList:true,subtree:true,characterData:true});applyLanguage();
}
