import{chromium}from'playwright-core';import{mkdir,writeFile}from'node:fs/promises';
await mkdir('artifacts/screenshots',{recursive:true});const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true});const page=await browser.newPage({viewport:{width:1536,height:1100}});const errors=[],requests=[];page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push(r.url()));
const language=process.env.LAB_LANGUAGE||'python',pubpkg=language==='python'?'py_pubsub':'cpp_pubsub',servicepkg=language==='python'?'py_service':'cpp_service';
const base=process.env.LAB_URL||(process.argv.includes('--built')?'http://127.0.0.1:8018/basics.html':'http://127.0.0.1:8017/basics.html');const card=i=>page.locator('.terminal-card').nth(i),text=i=>card(i).locator('.terminal-transcript pre');
async function command(i,line,{wait=true}={}){await page.waitForFunction(i=>/^Jazzy/.test(document.querySelectorAll('.terminal-state')[i]?.textContent),i,{timeout:180000});await card(i).locator('.xterm-helper-textarea').focus();await page.keyboard.insertText(line);await page.keyboard.press('Enter');await page.waitForTimeout(100);if(!wait&&/^ros2 (run|launch)/.test(line))await page.waitForFunction(i=>document.querySelectorAll('.terminal-state')[i].textContent.includes('callbacks ready'),i,{timeout:180000});if(wait)await page.waitForFunction(i=>/^Jazzy/.test(document.querySelectorAll('.terminal-state')[i].textContent),i,{timeout:180000});}
async function output(i,needle){await page.waitForFunction(([i,needle])=>document.querySelectorAll('.terminal-transcript pre')[i]?.textContent.includes(needle),[i,needle],{timeout:180000});}
async function stop(i){await card(i).locator('.xterm-helper-textarea').focus();await page.keyboard.press('Control+c');await page.waitForTimeout(200);}
async function unit(index){await page.locator(`button[data-index="${index}"]`).click();}
async function addFiles(limit=Infinity){const details=page.locator('#unit details');for(let i=0;i<Math.min(await details.count(),limit);i++){const item=details.nth(i);if(await item.getAttribute('open')===null)await item.locator('summary').click();const replace=item.getByRole('button',{name:'Replace with example',exact:true});if(await replace.count()){page.once('dialog',dialog=>dialog.accept());await replace.click();}else{await item.getByRole('button',{name:/^(Add file|Open file)$/}).click();}if((await page.locator('#status').innerText()).includes('first'))throw Error(await page.locator('#status').innerText());}}
async function screenshot(name){await page.screenshot({path:`artifacts/screenshots/${language==='cpp'?'cpp-':''}${name}.png`,fullPage:true});}
try{
 await page.goto(base);await page.getByRole('button',{name:'Start your first unit',exact:true}).click();await page.locator('.xterm').waitFor();await page.locator('#language').selectOption(language);
 await page.locator('#guide-mode').click();const envCommands=await page.locator('#unit .command code').allTextContents();for(const c of envCommands)await command(0,c);await output(0,'/opt/ros/jazzy/bin/ros2');if(requests.some(u=>u.includes('pyodide')||u.includes('wasm-clang')))throw Error('Heavy runtime loaded in Unit 1');await screenshot('unit-1');console.log('PASS visible environment unit; no runtime downloads');
 await unit(2);const wsCommands=await page.locator('#unit .command code').allTextContents();for(const c of wsCommands)await command(0,c);await output(0,"Package 'my_first_package' not found");await output(0,'Hi from my_first_package.');await screenshot('workspace-tree');console.log('PASS visible package/build/source unit');
 await unit(3);const pubCommands=await page.locator('#unit .command code').allTextContents();for(const c of pubCommands.slice(0,3))await command(0,c);await addFiles();for(const c of pubCommands.slice(3,6))await command(0,c);await screenshot('package-build');await command(0,pubCommands[6],{wait:false});await output(0,'Publishing:');await page.getByRole('button',{name:'+ Terminal',exact:true}).click();await command(1,pubCommands[7]);await command(1,pubCommands[8],{wait:false});await output(1,'I heard:');await screenshot('pubsub');console.log('PASS visible pub/sub in separate terminals');
 await page.getByRole('button',{name:'+ Terminal',exact:true}).click();for(const c of pubCommands.slice(9,14))await command(2,c);await command(2,'ros2 topic echo /topic',{wait:false});await output(2,'Hello World');await stop(2);await command(2,'ros2 topic info /topic');await output(2,'Subscription count: 1');
 await stop(0);await stop(1);await unit(4);await addFiles(1);const msgCommands=await page.locator('#unit .command code').allTextContents();
 // The visible custom package must be created before its Add file controls are used.
 for(const c of msgCommands.filter(c=>c==='cd ~/ros2_ws/src'||c.includes('pkg create')))await command(2,c);
 await addFiles();await command(2,'cd ~/ros2_ws');await command(2,'colcon build');await command(2,'source install/setup.bash');await command(0,`ros2 run ${pubpkg} talker`,{wait:false});await output(0,'Publishing:');await command(2,'ros2 param set /talker message_prefix Hello');await output(0,'Hello:');await stop(0);await command(0,`ros2 run ${pubpkg} status`,{wait:false});await command(2,'ros2 topic echo /status',{wait:false});await output(2,'Ada');await stop(0);await stop(2);console.log('PASS visible custom message and live parameter');
 await unit(5);const serviceCommands=await page.locator('#unit .command code').allTextContents();for(const c of serviceCommands.slice(0,3))await command(2,c);await addFiles();await command(2,'cd ~/ros2_ws');await command(2,'colcon build');await command(2,'source install/setup.bash');await command(0,'source ~/ros2_ws/install/setup.bash');await command(0,`ros2 run ${servicepkg} server`,{wait:false});await page.waitForTimeout(1500);await command(2,"ros2 service call /add_two_ints example_interfaces/srv/AddTwoInts '{a: 7, b: 8}'");await output(2,'15');await stop(0);await command(0,`ros2 launch ${pubpkg} system.launch.py`,{wait:false});await output(0,'Launched');await screenshot('launch');await stop(0);console.log('PASS visible service and launch');
 await unit(6);const actionPackage=language==='cpp'?'cpp_actions':'py_actions';const actionCommands=await page.locator('#unit .command code').allTextContents();for(const c of actionCommands.slice(0,4))await command(2,c);await addFiles();await command(2,'cd ~/ros2_ws');await command(2,`colcon build --packages-select ${actionPackage}`);await command(2,'source install/setup.bash');await command(0,'source ~/ros2_ws/install/setup.bash');await command(0,`ros2 run ${actionPackage} server`,{wait:false});await page.waitForTimeout(500);
 await command(2,"ros2 action send_goal /fibonacci action_tutorials_interfaces/action/Fibonacci '{order: 6}' --feedback");await output(2,'Result status: 4');await command(2,`ros2 run ${actionPackage} cancel_client`);await output(2,'Result status: 5');await command(2,"ros2 action send_goal /fibonacci action_tutorials_interfaces/action/Fibonacci '{order: -1}'");await output(2,'Goal rejected');await stop(0);await screenshot('actions');console.log('PASS visible Actions package/build, CLI feedback, cancellation, rejection and cleanup');
 await unit(7);await page.getByRole('button',{name:'Start playground',exact:true}).click();await command(0,"ros2 topic pub -r 5 /cmd_vel geometry_msgs/msg/Twist '{linear: {x: 0.2}}'",{wait:false});await page.waitForTimeout(700);await stop(0);await command(0,"ros2 topic pub --once /cmd_vel geometry_msgs/msg/Twist '{}'");await page.locator('#unit').evaluate(el=>el.scrollTop=0);await screenshot('playground');await page.getByRole('button',{name:'Stop playground',exact:true}).click();console.log('PASS playground');
 if(errors.length)throw Error(errors.join('\n'));await writeFile('artifacts/acceptance-'+language+'.json',JSON.stringify({passed:true,errors,requests:requests.length},null,2));console.log('PASS fresh-profile visible-course acceptance');
}catch(e){console.error(await page.locator('.terminal-transcript pre').allTextContents());await screenshot('acceptance-failure');console.error(e);console.error(await page.locator('.terminal-transcript pre').allTextContents());process.exitCode=1;}finally{await browser.close();}
