#!/usr/bin/env python3
"""Preserve installed Jazzy definitions and native expanded display text.
Source /opt/ros/jazzy/setup.bash; run from this project root. --check detects drift.
"""
import contextlib, io, json, pathlib, subprocess, sys
from ros2interface.verb.show import _show_interface
from rosidl_runtime_py import get_interface_path
names=json.loads(subprocess.check_output(['node','--input-type=module','-e',"import {BUILTIN} from './src/interfaces/builtin.js'; console.log(JSON.stringify(Object.keys(BUILTIN)))"],text=True))
records={}
for name in names:
    record={'source':pathlib.Path(get_interface_path(name)).read_text()}
    for key,comments,nested in [('default',True,False),('all',True,True),('none',False,False)]:
        output=io.StringIO()
        with contextlib.redirect_stdout(output):
            _show_interface(name,is_show_comments=comments,is_show_nested_comments=nested)
        record[key]=output.getvalue().removesuffix('\n')
    records[name]=record
path=pathlib.Path('src/interfaces/native-text.js')
content='// Generated by scripts/capture-interface-text.py from installed ROS 2 Jazzy.\n// Original upstream comments and formatting; see NOTICE and docs/INTERFACES.md.\nexport const NATIVE_INTERFACE_TEXT = '+json.dumps(records,ensure_ascii=False,indent=2)+';\n'
if '--check' in sys.argv:
    assert path.read_text()==content,'Interface text differs from native Jazzy; inspect before regenerating.'
    print('PASS:',len(records),'definitions and all three display modes match native Jazzy')
else:
    path.write_text(content)
    print('Captured',len(records),'native interface definitions with comments and nested display modes')
