import {readFile,writeFile} from 'node:fs/promises';
import {CPP_RUNTIME_HEADERS} from '../src/runtime-catalog.js';
// Keep readable installed files identical to the browser runtime sources.
const files={};
for(const [path,file] of Object.entries(CPP_RUNTIME_HEADERS))files[path]=await readFile(new URL('../src/cpp/'+file,import.meta.url),'utf8');
const python=await readFile(new URL('../src/python/compat.py',import.meta.url),'utf8');
const modules=[...new Set([...python.matchAll(/_module\('([^']+)'/g)].map(match=>match[1]))];
const output='// Generated by scripts/installation-assets.mjs; edit the runtime sources.\nexport const RUNTIME_FILES='+JSON.stringify({files,python,modules})+';\n';
const target=new URL('../src/installation-assets.js',import.meta.url);
if(process.argv.includes('--check')){if(await readFile(target,'utf8')!==output)throw Error('Stale simulated ROS assets: run npm run bundle:installation');}
else await writeFile(target,output);
